apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ template "imagepullsecret-patcher.fullname" . }}-dockerconfigjson
  labels:
    app: {{ template "imagepullsecret-patcher.fullname" . }}
    chart: "{{ .Chart.Name }}"
    release: {{ .Release.Name }}
data:
  .dockerconfigjson: {{.Values.dockerConfigJsonBase64Encoded}}